/*
* Copyright (c) 2015 Amazon.com. All rights reserved. 
*/
var g={SUCCESS:0,HTML_LOAD_FAILURE:1,INJECTION_FAILURE:2,JAVASCRIPT_FAILURE:3,INTERNAL_FAILURE:4,INVALID_ARGUMENTS:5,DOCUMENT_INVALID:6,INCOMPATIBLE_PHANTOMJS:7,MEDIA_QUERY_USED_FOR_NON_FIXED_LAYOUT:8,FAILURE_FROM_SIMULATOR:9,UNSUPPORTED_PSEUDO_SELECTORS:10,MEDIA_QUERY_USED_FOR_FIXED_LAYOUT:11,UNSUPPORTED_VALUE_FROM_TOP_DOWN_TRANSFORMER:12,FONT_SIZE_ZERO:14,PREPROCESS_TRANSFORMER_FAILED:15,PATTERN_FAILURE_START:20,PATTERN_FAILURE_FLOAT_LEFT_CLEAR_BOTH:21,PATTERN_FAILURE_FLOAT_RIGHT_CLEAR_BOTH:22,
PATTERN_FAILURE_FLOAT_LEFT_CLEAR_LEFT:23,PATTERN_FAILURE_FLOAT_RIGHT_CLEAR_RIGHT:24,PATTERN_FAILURE_MINH_POS_ABS_HEIGHT:25,PATTERN_FAILURE_DISPLAY_INLINE_BOXSIZING:26,PATTERN_FAILURE_WEBKIT_TRANSFORM_TRANSLATE:27,PATTERN_FAILURE_WEBKIT_TRANSFORM_ROTATEX:28,PATTERN_FAILURE_WEBKIT_TRANSFORM_ROTATEY:29,PATTERN_FAILURE_WEBKIT_TRANSFORM_ROTATE3d:30,PATTERN_FAILURE_WEBKIT_TRANSFORM_SCALE3d:31,PATTERN_FAILURE_BGIMAGE_LINEAR_GRADIENT:32,PATTERN_FAILURE_BACKGROUND_COLOR_MARGIN_LEFT_INLINE:33,PATTERN_FAILURE_BACKGROUND_COLOR_MARGIN_RIGHT_INLINE:34,
PATTERN_FAILURE_BACKGROUND_IMAGE_MARGIN_LEFT_INLINE:35,PATTERN_FAILURE_BACKGROUND_IMAGE_MARGIN_RIGHT_INLINE:36,PATTERN_FAILURE_END:121,RULE_FAILURE_UNSUPPORTED_COUNTER_TYPE_WITH_INLINE_BLOCK:130,RULE_FAILURE_UNSUPPORTED_CONTENT_BEFORE_LI:131,RULE_FAILURE_FIRSTLINE_UNSUPPORTED_DISPLAY_TAG:132,RULE_FAILURE_INLINECHILD_UNSUPPORTED_DISPLAY_TAG:133,RULE_FAILURE_FIRSTLETTER_UNSUPPORTED:134,RULE_FAILURE_FIRSTLETTER_NOT_FOUND:135,EMPTY_TAG_AFTER_FLOAT:136,DROP_CAP_PARA_LINE_HEIGHT_ZERO:137,MATHML_UNSUPPORTED_TAG:138,
UNSUPPORTED_PSEUDO_SELECTOR:141},h="main.js ",h=h+"--inputhtml <input html file> ",h=h+"--outputhtml <output html file> ",h=h+"[--outputencoding <encoding>] ",h=h+"[--urlrelative true/false] ",h=h+"[--inlinecss true/false] ",h=h+"[--analyzermode true/false] ",h=h+"[--metricspath <metrics file path>] ",h=h+"[--help]",k=(new Date).getTime(),l={error:function(a){console.error("[ERROR] : "+a)},warn:function(a){console.warn("[WARNING] : "+a)},info:function(a){console.log("[INFO]  : "+a)}};
function m(a,b){a.injectJs(b)||(n.J(b)||console.log("File "+b+" doesnt exist"),l.error("Internal Failure : Error in injecting "+b),phantom.exit(g.INJECTION_FAILURE))}function q(){var a=require("system").env;if("PHANTOMJS_EXIT_MARKER_FILE"in a){var a=a.PHANTOMJS_EXIT_MARKER_FILE,b=require("fs");null!==a&&""!=a.trim()&&b.exists(a)&&b.remove(a)}l.info("*** Successfully Converted ****");phantom.exit(0)}
var n={b:function(a){var b=require("fs");if(!b.isFile(a))return null;a=b.open(a,"r");b=a.read();a.close();return b},c:function(a,b,e){null==e&&(e="UTF-8");try{var c=require("fs").open(a,{charset:e,mode:"w"});c.writeLine(b);c.close()}catch(d){console.log("Unable to write to file. Error: "+d)}},a:function(a){return require("fs").absolute(a)},J:function(a){var b=require("fs"),e=document.location.pathname,e=e.substring(0,e.lastIndexOf(b.separator)+1);return b.isFile(e+a)?!0:!1}},r={width:1200,height:1E3};
n.g=function(a){var b=navigator.appVersion;a=a.replace(/\\/g,"/");a=encodeURI(a);-1!=b.indexOf("Win")&&(a="file:///"+a);return a};
var t={errorCodeList:{SUCCESS:{id:0,category:"SKIPPABLE",desc:"Success"},HTML_LOAD_FAILURE:{id:1,category:"FATAL",desc:"HTML Load Failure"},INJECTION_FAILURE:{id:2,category:"FATAL",desc:"Injection Failure"},JAVASCRIPT_FAILURE:{id:3,category:"FATAL",desc:"Javascript Failure"},INTERNAL_FAILURE:{id:4,category:"FATAL",desc:"Internal failure occured during processing"},INVALID_ARGUMENTS:{id:5,category:"FATAL",desc:"Invalid Arguments"},DOCUMENT_INVALID:{id:6,category:"FATAL",desc:"Document Invalid"},INCOMPATIBLE_PHANTOMJS:{id:7,
category:"FATAL",desc:"Incompatible PhantomJS"},MEDIA_QUERY_USED_FOR_NON_FIXED_LAYOUT:{id:8,category:"SKIPPABLE",desc:"Mobi Media Query used for Non Fixed Layout Book"},FAILURE_FROM_SIMULATOR:{id:9,category:"SKIPPABLE",desc:"Preprocessor Failure from simulator."},UNSUPPORTED_PSEUDO_SELECTORS:{id:10,category:"SKIPPABLE",desc:"Unsupported pseudo selectors used, hence failing"},MEDIA_QUERY_USED_FOR_FIXED_LAYOUT:{id:11,category:"SKIPPABLE",desc:"Unsupported Media Query used for Fixed Layout Book"},UNSUPPORTED_VALUE_FROM_TOP_DOWN_TRANSFORMER:{id:12,
category:"SKIPPABLE",desc:"Unsupported Value From Top Down Transformer"},FIXED_LAYOUT_WITH_TEXT:{id:13,category:"SKIPPABLE",desc:"FL Book with text is not supported"},FONT_SIZE_ZERO:{id:14,category:"SKIPPABLE",desc:"Font Size Zero"},PREPROCESS_TRANSFORMER_FAILED:{id:15,category:"SKIPPABLE",desc:"Internal failure occured during processing"},BOX_POSITION_CALCULATION_FAILURE:{id:16,category:"SKIPPABLE",desc:"Box Positions can not be calcuated for non box elements"},OBJECT_NOT_INITIALIZED:{id:17,category:"SKIPPABLE",
desc:"The object has not been initialized : "},VALIDATOR_FAILURE:{id:18,category:"FATAL",desc:"Validator encountered a failure : "},INVALID_PROPERTY_VALUE:{id:19,category:"SKIPPABLE",desc:"Unexpected call happened to fetch value."},PATTERN_FAILURE_START:{id:20,category:"UNUSED",desc:"Unused Error Code marking the start of pattern failure error codes."},PATTERN_FAILURE_FLOAT_LEFT_CLEAR_BOTH:{id:21,category:"SKIPPABLE",desc:"Pattern Failure Float Left Clear Both"},PATTERN_FAILURE_FLOAT_RIGHT_CLEAR_BOTH:{id:22,
category:"SKIPPABLE",desc:"Pattern Failure Float Right Clear Both"},PATTERN_FAILURE_FLOAT_LEFT_CLEAR_LEFT:{id:23,category:"SKIPPABLE",desc:"Pattern Failure Float Left Clear Left"},PATTERN_FAILURE_FLOAT_RIGHT_CLEAR_RIGHT:{id:24,category:"SKIPPABLE",desc:"Pattern Failure Float Right Clear Right"},PATTERN_FAILURE_MINH_POS_ABS_HEIGHT:{id:25,category:"SKIPPABLE",desc:"Pattern Failure Min H Pos Abs Height"},PATTERN_FAILURE_DISPLAY_INLINE_BOXSIZING:{id:26,category:"SKIPPABLE",desc:"Pattern Failure Display Inline Boxsizing"},
PATTERN_FAILURE_WEBKIT_TRANSFORM_TRANSLATE:{id:27,category:"SKIPPABLE",desc:"Pattern Failure Webkit Transform Translate"},PATTERN_FAILURE_WEBKIT_TRANSFORM_ROTATEX:{id:28,category:"SKIPPABLE",desc:"Pattern Failure Webkit Transform Rotate X"},PATTERN_FAILURE_WEBKIT_TRANSFORM_ROTATEY:{id:29,category:"SKIPPABLE",desc:"Pattern Failure Webkit Transform Rotate Y"},PATTERN_FAILURE_WEBKIT_TRANSFORM_ROTATE3d:{id:30,category:"SKIPPABLE",desc:"Pattern Failure Webkit Transform Rotate 3D"},PATTERN_FAILURE_WEBKIT_TRANSFORM_SCALE3d:{id:31,
category:"SKIPPABLE",desc:"Pattern Failure Webkit Transform Scale 3D"},PATTERN_FAILURE_BGIMAGE_LINEAR_GRADIENT:{id:32,category:"SKIPPABLE",desc:"Pattern Failure Background Image Linear Gradient"},PATTERN_FAILURE_BACKGROUND_COLOR_MARGIN_LEFT_INLINE:{id:33,category:"SKIPPABLE",desc:"Pattern Failure Background Color Margin Left Inline"},PATTERN_FAILURE_BACKGROUND_COLOR_MARGIN_RIGHT_INLINE:{id:34,category:"SKIPPABLE",desc:"Pattern Failure Background Color Margin Right Inline"},PATTERN_FAILURE_BACKGROUND_IMAGE_MARGIN_LEFT_INLINE:{id:35,
category:"SKIPPABLE",desc:"Pattern Failure Background Image Margin Left Inline"},PATTERN_FAILURE_BACKGROUND_IMAGE_MARGIN_RIGHT_INLINE:{id:36,category:"SKIPPABLE",desc:"Pattern Failure Background Image Margin Right Inline"},PATTERN_FAILURE_END:{id:121,category:"UNUSED",desc:"Unused Error Code marking the end of pattern failure error codes."},RULE_FAILURE_UNSUPPORTED_COUNTER_TYPE_WITH_INLINE_BLOCK:{id:130,category:"SKIPPABLE",desc:"Counter type is not supported with inline-block."},RULE_FAILURE_UNSUPPORTED_CONTENT_BEFORE_LI:{id:131,
category:"SKIPPABLE",desc:"li tag cannot be handled for the given html file. Selector & HtmlFile :: "},RULE_FAILURE_FIRSTLINE_UNSUPPORTED_DISPLAY_TAG:{id:132,category:"SKIPPABLE",desc:"FirstLine::first-line is applied to unsupported display tag. Display = "},RULE_FAILURE_INLINECHILD_UNSUPPORTED_DISPLAY_TAG:{id:133,category:"SKIPPABLE",desc:"FirstLine::Inline node is having child nodes with unsupported display. Display = "},RULE_FAILURE_FIRSTLETTER_UNSUPPORTED:{id:134,category:"SKIPPABLE",desc:"first-letter cannot be handled for the given html file. HtmlFile ::"},
RULE_FAILURE_FIRSTLETTER_NOT_FOUND:{id:135,category:"SKIPPABLE",desc:"FirstLetter::Could not find valid first letter content"},EMPTY_TAG_AFTER_FLOAT:{id:136,category:"SKIPPABLE",desc:"Found empty tag without explicit height after a float"},DROP_CAP_PARA_LINE_HEIGHT_ZERO:{id:137,category:"SKIPPABLE",desc:"Found dropcap paragraph with zero line height"},MATHML_UNSUPPORTED_TAG:{id:138,category:"SKIPPABLE",desc:"Found unsupported mathml tag"},UNSUPPORTED_QUERY_SELECTOR:{id:140,category:"SKIPPABLE",desc:"Found unsupported query selector"},
UNSUPPORTED_PSEUDO_SELECTOR:{id:141,category:"SKIPPABLE",desc:"Found unsupported pseudo selector"},NO_PRESENTATION_MATHML_FOUND:{id:142,category:"SKIPPABLE",desc:"No presentation mathml found inside semantics tag"}},A:function(a){return(a=t.f(a))?a.id:-1},K:function(a){return(a=t.f(a))?a.category:-1},f:function(a){return t.errorCodeList[a]}};
function u(){this.m=n;this.data={};this.data.htmlOutput=[];this.data.hasMobi7OrMobi8MediaQuery=!1;this.data.isHorizontalPropertyRelativized=!1;this.data.unsupListOfMQs=[]}function v(a){var b=retVal.unsupListOfMQs;a.data.unsupListOfMQs=[];a.data.unsupListOfMQs.push(b)}
var w={C:function(a){if("string"!==typeof a)return null;var b=a.split(",");if(2>b.length)return null;for(var e=a=NaN,c=0;c<b.length;c++){var d=b[c].split("=");if(2==d.length){var f=d[0].trim().toLowerCase(),d=d[1].trim().toLowerCase();if("width"==f){var A=parseInt(d);NaN!=A&&(a=A)}"height"==f&&(f=parseInt(d),NaN!=f&&(e=f))}}return NaN!=a&&NaN!=e?(b={},b.width=a,b.height=e,b):null},B:function(a){if(null==a||void 0==a||a.nodeType!==Node.ELEMENT_NODE)return null;var b=a.getAttribute("name");if("string"!==
typeof b)return null;b=b.trim().toLowerCase();if("viewport"!==b)return null;a=a.getAttribute("content");if("string"!==typeof a)return null;a=a.trim().toLowerCase();a=this.C(a);return null==a?null:a},o:function(a){if("string"!==typeof a)return null;a=n.b(a.trim());return"string"!==typeof a||0>=a.trim().length?null:(new DOMParser).parseFromString(a,"text/xml")},I:function(a){a=a.getElementsByTagName("meta");if(0>=a.length)return null;for(var b=0;b<a.length;b++){metaTag=a[b];var e=this.B(metaTag);if(e)return e}return null},
F:function(a){return(a=this.o(a))?this.I(a):null}};phantom.injectJs("scriptInjector.js")||(console.error("[ERROR] : Initialization Error: Failed to Inject scriptInjector.js"),phantom.exit(1));
try{var system=require("system");if(1==system.args.length||2==system.args.length&&"--help"==system.args[1])console.log(h),phantom.exit(0);2>system.args.length&&(l.error("Input Arguments are not Valid"),phantom.exit(g.INVALID_ARGUMENTS));var x={},y=!1;if(2==system.args.length)var z=n.a(system.args[1]),B=n.b(z),x=JSON.parse(B);else if(4==system.args.length&&"drop-style-mode"===system.args[1])l.info("Starting drop style handler"),y=!0;else{x.htmlFiles=[];var C="",D="";x.outputEncoding="UTF-8";x.inlineCSS=
!0;x.lineHeightRelativize=!0;x.isURLRelative=!0;x.metricsFilePath="/tmp/metrics.json";x.enableMathML=!1;var E="[",E=E+'{"name": "CAN-LF", "fontSize": "8px","width": "512px" },',E=E+'{"name": "CAN-MF", "fontSize": "16px","width": "512px" },',E=E+'{"name": "CAN-HF", "fontSize": "32px","width": "512px" },',E=E+'{"name": "EINK-LF", "fontSize": "8px","width": "800px" },',E=E+'{"name": "EINK-MF", "fontSize": "16px","width": "800px" },',E=E+'{"name": "EINK-HF", "fontSize": "32px","width": "800px" }',E=E+
"]";x.renditionSetting=JSON.parse(E);for(var F=1;F<system.args.length&&(0!=system.args[F].indexOf("--")||F!=system.args.length-1);F++)"--inputhtml"==system.args[F]&&(C=system.args[F+1]),"--outputhtml"==system.args[F]&&(D=system.args[F+1]),"--outputencoding"==system.args[F]&&(x.outputEncoding=system.args[F+1]),"--urlrelative"==system.args[F]&&"false"==system.args[F+1].toLowerCase()&&(x.isURLRelative=!1),"--inlinecss"==system.args[F]&&"false"==system.args[F+1].toLowerCase()&&(x.inlineCSS=!1),"--metricspath"==
system.args[F]&&(x.metricsFilePath=system.args[F+1]),"--analyzermode"==system.args[F]&&"true"==system.args[F+1].toLowerCase()&&(x.analyzerMode=!0);if(""==C.trim()||""==D.trim())l.error("Input and Output Html Files are mandatory"),phantom.exit(g.INVALID_ARGUMENTS);var G={};G.inputHtml=C;G.outputHtml=D;x.htmlFiles.push(G)}var H=new u;x.unsupListOfMQs=[];l.info("Starting HTML Processing");if(y){var z=n.a(system.args[2]),B=n.b(z),I=n.a(system.args[3]),J=JSON.parse(B);K(J,[],I)}else x.analyzerMode?processHtmlsInAnalyzerMode(x,
H):L(x,H)}catch(M){l.error(M),phantom.exit(g.INVALID_ARGUMENTS)}
function L(a,b){function e(){retVal=c.evaluate(function(a){try{return doProcessingOnWebPage(a)}catch(b){a={};var c=JSON.stringify(b,null,4),c=JSON.parse(c),d=c.errorCode;void 0!=d?(a.status=d,a.message=c.errorMessage):(a.status="INTERNAL_FAILURE",a.message=b);return a}},a);retVal.status!==g.SUCCESS&&phantom.exit(t.A(retVal.status));c.release();n.c(f.outputHtml,retVal.htmlContent,a.outputEncoding);l.info("Finished Writing into File "+f.outputHtml);var d=JSON.parse(retVal.fontFaceContent),e=JSON.parse(retVal.errorStack),
p={};p.htmlFile=f.inputHtml;p.fontFaceRules=d.fontFaceRules;p.featureInfo=retVal.featureInfo;p.isFlWithText=retVal.isFlWithText;p.errorInfo=e.errorInfo;b.data.htmlOutput.push(p);v(b);b.data.hasMobi7OrMobi8MediaQuery=retVal.hasMobi7OrMobi8MediaQuery;b.data.isHorizontalPropertyRelativized=retVal.isHorizontalPropertyRelativized;a.htmlFiles.pop();0===a.htmlFiles.length?(b.data.preprocessorStartTime=k,b.data.preprocessorEndTime=(new Date).getTime(),b.m.c(a.metricsFilePath,JSON.stringify(b.data,null,2),
"UTF-8"),q()):(a.unsupListOfMQs=retVal.unsupListOfMQs,L(a,b))}var c=require("webpage").create(),d=a.viewPortDimensions,f=a.htmlFiles[a.htmlFiles.length-1];if(a.handleViewPort){if("object"!==typeof d||"number"!==typeof d.width||"number"!==typeof d.height)d=w.F(f.inputHtml);d&&(c.viewportSize={width:d.width,height:d.height},a.viewPortDimension=d)}if(a.relativizeUnits||a.textIndentRelativize)c.viewportSize={width:1200,height:1920};c.onConsoleMessage=function(a){l.info(a)};c.onError=function(a,b){var c=
"JAVASCRIPT_FAILURE",d;try{d=JSON.parse(a)}catch(e){d=null}null!=d&&(a=d.message,c=d.errorCode);l.error("PHANTOMJS: ***Error: "+a);b.forEach(function(a){l.error(a.file+":"+a.line)});phantom.exit(g[c])};c.onCallback=function(){e()};entityResolvedFilePath=n.g(f.inputHtml);c.open(entityResolvedFilePath,function(b){if("success"!==b)l.error("Failed to load HTML file "+f.inputHtml),phantom.exit(g.HTML_LOAD_FAILURE);else if(l.info("Conversion started for file : "+f.inputHtml),m(c,"coreprocessor.js"),a.enableMathML)if(c.evaluate(function(){switchHiddenAndShowClass(document)}),
!0===c.evaluate(function(){return 0<document.querySelectorAll('math:not([style*="display:none"]),mml\\:math:not([style*="display:none"])').length?!0:!1}))m(c,"MathJax.js"),c.evaluate(function(a){cleanUpEmptyMathContent(document);preProcessMathContent(document);preProcessMathmlSemanticsTag(document,a.skipFailures);addNamespace(document);for(var b=document.getElementsByTagName("mstyle"),c=0;c<b.length;c++)b[c].removeAttribute("fontfamily");MathJax.Hub.Register.StartupHook("SVG Jax Ready",function(){MathJax.OutputJax.SVG.Augment({getBorders:function(a){var b=
{top:0,right:0,bottom:0,left:0},c=!1,d;for(d in b)if(b.hasOwnProperty(d)){var e="border"+d.charAt(0).toUpperCase()+d.substr(1),f=a[e+"Style"];f&&"none"!==f?(c=!0,b[d]=this.length2em(a[e+"Width"]||"3px"),b[d+"Style"]=a[e+"Style"],b[d+"Color"]=a[e+"Color"],"initial"===b[d+"Color"]&&(b[d+"Color"]="")):delete b[d]}return c?b:!1}})});MathJax.Hub.Register.MessageHook("Math Processing Error",function(a){throw a;});MathJax.Hub.Register.MessageHook("MathML Jax - parse error",function(a){throw a;});MathJax.Hub.Register.MessageHook("MathML Jax - unknown node type",
function(a){throw a;});MathJax.Hub.formatError=function(a,b){throwMathmlSpecificError(b)};validateSupportedTags(document.body,a.skipFailures);MathJax.Hub.queue.Push(function(){cleanMathJaxOutput();window.callPhantom()})},a);else c.onCallback();else c.onCallback()})}
function K(a,b,e){var c=require("webpage").create();c.viewportSize=r;c.onConsoleMessage=function(a){console.log(a)};c.onError=function(a){console.error(a)};var d=a[0],f=n.g(d.htmlFile);c.open(f,function(f){if("success"!==f)l.error("Could not load the file "+d.htmlFile+" : "+f),c.close(),phantom.exit(1);else try{m(c,"coreprocessor.js");var N=c.evaluate(function(a){try{return processHtmlFileForDropStyle(a)}catch(b){a="HTML : "+a.htmlFile+" Message : "+JSON.stringify(b,null,4),l.error(a),phantom.exit(1)}},
d);b.push(N)}catch(p){f="HTML : "+d.htmlFile+" Message : "+JSON.stringify(p,null,4),l.error(f),phantom.exit(1)}c.release();a.shift();0==a.length&&(n.c(e,JSON.stringify(b,null,2),"UTF-8"),q());K(a,b,e)})};
