/*
* Copyright (c) 2015 Amazon.com. All rights reserved. 
*/
var g={o:function(a){var b=require("fs");if(!b.isFile(a))return null;a=b.open(a,"r");b=a.read();a.close();return b},s:function(a,b,c){null==c&&(c="UTF-8");a=require("fs").open(a,{charset:c,mode:"w"});a.writeLine(b);a.close()},j:function(a){return require("fs").absolute(a)},m:function(a){var b=require("fs"),c=document.location.pathname,c=c.substring(0,c.lastIndexOf(b.separator)+1);return b.isFile(c+a)?!0:!1},getExtension:function(a){if(null===a||void 0===a)return null;a=a.trim();var b=a.lastIndexOf(".");
return-1===b?null:a.substring(b+1,a.length)}};"use strict";
var u={BLOCKS:[{block_start:0,block:"Latin"},{block_start:128,block:"Latin-1_Supplement"},{block_start:256,block:"Latin_Extended-A"},{block_start:384,block:"Latin_Extended-B"},{block_start:592,block:"IPA_Extensions"},{block_start:688,block:"Spacing_Modifier_Letters"},{block_start:768,block:"Combining_Diacritical_Marks"},{block_start:880,block:"Greek_Coptic"},{block_start:1024,block:"Cyrillic"},{block_start:1328,block:"Armenian"},{block_start:1424,block:"Hebrew"},{block_start:1536,block:"Arabic"},
{block_start:1792,block:"Syriac"},{block_start:1872,block:"Arabic"},{block_start:1920,block:"Thaana"},{block_start:1984,block:"Nko"},{block_start:2048,block:"Samaritan"},{block_start:2112,block:"Mandaic"},{block_start:2304,block:"Devanagari"},{block_start:2432,block:"Bengali"},{block_start:2560,block:"Gurmukhi"},{block_start:2688,block:"Gujarati"},{block_start:2816,block:"Oriya"},{block_start:2944,block:"Tamil"},{block_start:3072,block:"Telugu"},{block_start:3200,block:"Kannada"},{block_start:3328,
block:"Malayalam"},{block_start:3456,block:"Sinhala"},{block_start:3584,block:"Thai"},{block_start:3712,block:"Lao"},{block_start:3840,block:"Tibetan"},{block_start:4096,block:"Myanmar"},{block_start:4256,block:"Georgian"},{block_start:4352,block:"Hangul"},{block_start:4608,block:"Ethiopic"},{block_start:5024,block:"Cherokee"},{block_start:5120,block:"Canadian_Syllabics"},{block_start:5760,block:"Ogham"},{block_start:5792,block:"Runic"},{block_start:5888,block:"Tagalog"},{block_start:5920,block:"Hanunoo"},
{block_start:5952,block:"Buhid"},{block_start:5984,block:"Tagbanwa"},{block_start:6016,block:"Khmer"},{block_start:6144,block:"Mongolian"},{block_start:6320,block:"Canadian_Syllabics"},{block_start:6400,block:"Limbu"},{block_start:6480,block:"Tai_Le"},{block_start:6528,block:"New_Tai_Lue"},{block_start:6624,block:"Khmer"},{block_start:6656,block:"Buginese"},{block_start:6688,block:"Tai_Tham"},{block_start:6832,block:"Latin"},{block_start:6912,block:"Balinese"},{block_start:7040,block:"Sundanese"},
{block_start:7104,block:"Batak"},{block_start:7168,block:"Lepcha"},{block_start:7248,block:"Ol_Chiki"},{block_start:7296,block:"Cyrillic"},{block_start:7360,block:"Sundanese"},{block_start:7376,block:"Vedic"},{block_start:7424,block:"Phonetic_Extensions"},{block_start:7552,block:"Phonetic_Extensions_Supplement"},{block_start:7616,block:"Combining_Diacritical_Marks_Supplement"},{block_start:7680,block:"Latin_Extended_Additional"},{block_start:7936,block:"Greek_Coptic"},{block_start:8192,block:"Punctuation"},
{block_start:8304,block:"Letterlike"},{block_start:8400,block:"Combining_Diacritical_Marks_for_Symbols"},{block_start:8448,block:"Letterlike"},{block_start:8592,block:"Symbols"},{block_start:8704,block:"Mathematical"},{block_start:8960,block:"Symbols"},{block_start:9280,block:"Optical_Character_Recognition"},{block_start:9312,block:"Enclosed"},{block_start:9472,block:"Symbols"},{block_start:9984,block:"Dingbats"},{block_start:10176,block:"Mathematical"},{block_start:10224,block:"Symbols"},{block_start:10240,
block:"Braille_Patterns"},{block_start:10496,block:"Symbols"},{block_start:10624,block:"Mathematical"},{block_start:11008,block:"Symbols"},{block_start:11264,block:"Glagolitic"},{block_start:11360,block:"Latin_Extended-C"},{block_start:11392,block:"Greek_Coptic"},{block_start:11520,block:"Georgian"},{block_start:11568,block:"Tifinagh"},{block_start:11648,block:"Ethiopic"},{block_start:11744,block:"Cyrillic"},{block_start:11776,block:"Punctuation"},{block_start:11904,block:"CJK_Radicals_Supplement"},
{block_start:12032,block:"Kangxi_Radicals"},{block_start:12272,block:"Ideographic_Description_Characters"},{block_start:12288,block:"CJK_Symbols_And_Punctuation"},{block_start:12352,block:"Hiragana_Katakana"},{block_start:12544,block:"Bopomofo"},{block_start:12592,block:"Hangul"},{block_start:12688,block:"Kanbun"},{block_start:12704,block:"Bopomofo"},{block_start:12736,block:"CJK_Strokes"},{block_start:12784,block:"Hiragana_Katakana"},{block_start:12800,block:"Hangul"},{block_start:12832,block:"Enclosed"},
{block_start:12896,block:"Hangul"},{block_start:12928,block:"Enclosed"},{block_start:13312,block:"CJK_Ideographs_BMP"},{block_start:19904,block:"Yijing_Hexagram_Symbols"},{block_start:19968,block:"CJK_Ideographs_BMP"},{block_start:40960,block:"Yi"},{block_start:42192,block:"Lisu"},{block_start:42240,block:"Vai"},{block_start:42560,block:"Cyrillic"},{block_start:42656,block:"Bamum"},{block_start:42752,block:"Modifier_Tone_Letters"},{block_start:42784,block:"Latin_Extended-D"},{block_start:43008,block:"Syloti_Nagri"},
{block_start:43056,block:"Indic_Number_Forms"},{block_start:43072,block:"Phags_pa"},{block_start:43136,block:"Saurashtra"},{block_start:43232,block:"Devanagari"},{block_start:43264,block:"Kayah_Li"},{block_start:43312,block:"Rejang"},{block_start:43360,block:"Hangul"},{block_start:43392,block:"Javanese"},{block_start:43488,block:"Myanmar"},{block_start:43520,block:"Cham"},{block_start:43616,block:"Myanmar"},{block_start:43648,block:"Tai_Viet"},{block_start:43744,block:"Meetei_Mayek"},{block_start:43776,
block:"Ethiopic"},{block_start:43824,block:"Latin"},{block_start:43888,block:"Cherokee"},{block_start:43968,block:"Meetei_Mayek"},{block_start:44032,block:"Hangul"},{block_start:55216,block:"Hangul"},{block_start:57344,block:"PUA"},{block_start:63744,block:"CJK_Ideographs_BMP"},{block_start:64256,block:"Alphabetic_Presentation_Forms"},{block_start:64272,block:"Armenian"},{block_start:64285,block:"Hebrew"},{block_start:64336,block:"Arabic"},{block_start:65040,block:"Vertical_Forms"},{block_start:65056,
block:"Combining_Half_Marks"},{block_start:65072,block:"CJK_Symbols_And_Punctuation"},{block_start:65136,block:"Arabic"},{block_start:65280,block:"CJK_Symbols_And_Punctuation"},{block_start:65440,block:"Hangul"},{block_start:65504,block:"CJK_Symbols_And_Punctuation"},{block_start:65520,block:"Specials"},{block_start:65536,block:"Linear_B"},{block_start:65792,block:"Ancient_Greek"},{block_start:65936,block:"Letterlike"},{block_start:66E3,block:"Phaistos_Disc"},{block_start:66176,block:"Lycian"},{block_start:66208,
block:"Carian"},{block_start:66272,block:"Coptic"},{block_start:66304,block:"Old_Italic"},{block_start:66352,block:"Gothic"},{block_start:66384,block:"Old_Permic"},{block_start:66432,block:"Ugaritic"},{block_start:66464,block:"Old_Persian"},{block_start:66560,block:"Deseret"},{block_start:66640,block:"Shavian"},{block_start:66688,block:"Osmanya"},{block_start:66816,block:"Elbasan"},{block_start:66864,block:"Caucasian_Albanian"},{block_start:67072,block:"Linear_A"},{block_start:67584,block:"Cypriot_Syllabary"},
{block_start:67648,block:"Imperial_Aramaic"},{block_start:67680,block:"Palmyrene"},{block_start:67712,block:"Nabataean"},{block_start:67808,block:"Hatran"},{block_start:67840,block:"Phoenician"},{block_start:67872,block:"Lydian"},{block_start:67968,block:"Meroitic"},{block_start:68096,block:"Kharoshthi"},{block_start:68192,block:"Old_South_Arabian"},{block_start:68224,block:"Old_North_Arabian"},{block_start:68288,block:"Manichaean"},{block_start:68352,block:"Avestan"},{block_start:68416,block:"Inscriptional_Parthian"},
{block_start:68448,block:"Inscriptional_Pahlavi"},{block_start:68480,block:"Psalter_Pahlavi"},{block_start:68608,block:"Old_Turkic"},{block_start:68736,block:"Old_Hungarian"},{block_start:69216,block:"Rumi_Numeral_Symbols"},{block_start:69632,block:"Brahmi"},{block_start:69760,block:"Kaithi"},{block_start:69840,block:"Sora_Sompeng"},{block_start:69888,block:"Chakma"},{block_start:69968,block:"Mahajani"},{block_start:70016,block:"Sharada"},{block_start:70112,block:"Sinhala"},{block_start:70144,block:"Khojki"},
{block_start:70272,block:"Multani"},{block_start:70320,block:"Khudawadi"},{block_start:70400,block:"Grantha"},{block_start:70656,block:"Newa"},{block_start:70784,block:"Tirhuta"},{block_start:71040,block:"Siddham"},{block_start:71168,block:"Modi"},{block_start:71264,block:"Mongolian"},{block_start:71296,block:"Takri"},{block_start:71424,block:"Ahom"},{block_start:71840,block:"Warang_Citi"},{block_start:72384,block:"Pau_Cin_Hau"},{block_start:72704,block:"Bhaiksuki"},{block_start:72816,block:"Marchen"},
{block_start:73728,block:"Cuneiform"},{block_start:77824,block:"Egyptian_Hieroglyphs"},{block_start:82944,block:"Anatolian_Hieroglyphs"},{block_start:92160,block:"Bamum"},{block_start:92736,block:"Mro"},{block_start:92880,block:"Bassa_Vah"},{block_start:92928,block:"Pahawh_Hmong"},{block_start:93952,block:"Miao"},{block_start:94208,block:"Tangut"},{block_start:110592,block:"Hiragana_Katakana"},{block_start:113664,block:"Duployan"},{block_start:118784,block:"Musical"},{block_start:119296,block:"Ancient_Greek"},
{block_start:119552,block:"Tai_Xuan_Jing_Symbols"},{block_start:119648,block:"Counting_Rod_Numerals"},{block_start:119808,block:"Mathematical"},{block_start:120832,block:"Sutton_SignWriting"},{block_start:122880,block:"Glagolitic"},{block_start:124928,block:"Mende_Kikakui"},{block_start:125184,block:"Adlam"},{block_start:126464,block:"Arabic"},{block_start:126976,block:"Mahjong_Tiles"},{block_start:127024,block:"Domino_Tiles"},{block_start:127136,block:"Playing_Cards"},{block_start:127232,block:"Enclosed"},
{block_start:127744,block:"Symbols"},{block_start:131072,block:"CJK_Ideographs_SIP"},{block_start:983040,block:"PUA"},{block_start:1114112,block:"Invalid"}],BLOCK_TO_FONT_MAP:{Latin:["ccl","ds","bo","ba"],"Latin-1_Supplement":["ccl","ds","bo","ba"],"Latin_Extended-A":["ccl","ds","bo","ba"],Greek_Coptic:["bo","obs-c2000","unobs-c2000"],Cyrillic:["ccl","bo","ba"],Gujarati:["sa"],Malayalam:["ml"],Tamil:["mu"],CJK_Ideographs_SIP:["tbm","ss","songtc","nsk"],CJK_Ideographs_BMP:["tbm","ss","songtc","nsk"],
Hiragana_Katakana:["tbm","tbg"],CJK_Radicals_Supplement:["heitc","obs-c2000","unobs-c2000"],Kanbun:["tbm","tbg"],Bopomofo:["heitc"],Ideographic_Description_Characters:["ss","stH","heitc","myht"],Vertical_Forms:["songtc","tbm","tbg"],Punctuation:["bo"],Arabic:["nn","dm","sk"],Devanagari:["de"],Vedic:["de"],Indic_Number_Forms:["de","sa"],Specials:["bo"],Hangul:["nsk","ss","songtc","tbm"],Default:["obs-c2000","unobs-c2000"]},BLOCK_TO_FONT_MAP_PDF:{Latin:["bo"],Latin_Serif:["bo"],"Latin_Sans-Serif":["em"],
"Latin-1_Supplement":["bo"],"Latin_Extended-A":["bo"],Greek_Coptic:["bo","obs-c2000","unobs-c2000"],Cyrillic:["bo"],Gujarati:["sa"],Malayalam:["ml"],Tamil:["mu"],CJK_Ideographs_SIP:["tbm","ss","songtc","nsk"],CJK_Ideographs_BMP:["tbm","ss","songtc","nsk"],Hiragana_Katakana:["tbm","tbg"],CJK_Radicals_Supplement:["heitc","obs-c2000","unobs-c2000"],Kanbun:["tbm","tbg"],Bopomofo:["heitc"],Ideographic_Description_Characters:["ss","stH","heitc","myht"],Vertical_Forms:["songtc","tbm","tbg"],Punctuation:["bo"],
Arabic:["nn","dm","sk"],Devanagari:["de"],Vedic:["de"],Indic_Number_Forms:["de","sa"],Specials:["bo"],Hangul:["nsk","ss","songtc","tbm"],Default:["obs-c2000","unobs-c2000"]},FONT_TO_TYPEFACE_MAP:{georgia:1,arial:2,"sans-serif":2,calibri:2,"helvetica neue":2,"times new roman":1,serif:1,helvetica:2,baskerville:1,palatino:1,verdana:2,times:1},FONT_SIZE_FALLBACK_MAP:{"times new roman":.84,times:.88,serif:.86,helvetica:.965,"helvetica neue":.965,calibri:.89,georgia:.91,arial:.96,"sans-serif":.989,palatino:.89,
baskerville:.87},MAX_CODE_POINT:1114111,MIN_CODE_POINT:0,BLOCKS_WITH_UNSUPPORTED_COMBINATIONS:"Arabic Devanagari Bengali Gurmukhi Hangul Malayalam Musical Combining_Diacritical_Marks Combining_Diacritical_Marks_for_Symbols Combining_Diacritical_Marks_Supplement Combining_Half_Marks".split(" "),b:function(a){return u.BLOCK_TO_FONT_MAP[a]?u.BLOCK_TO_FONT_MAP[a]:u.BLOCK_TO_FONT_MAP.Default},l:function(a,b){return"Latin"==a&&1==u.FONT_TO_TYPEFACE_MAP[b]?u.BLOCK_TO_FONT_MAP_PDF.Latin_Serif:"Latin"==a&&
2==u.FONT_TO_TYPEFACE_MAP[b]?u.BLOCK_TO_FONT_MAP_PDF["Latin_Sans-Serif"]:u.BLOCK_TO_FONT_MAP_PDF[a]?u.BLOCK_TO_FONT_MAP_PDF[a]:u.BLOCK_TO_FONT_MAP_PDF.Default},c:function(a){if(a<this.MIN_CODE_POINT||a>this.MAX_CODE_POINT)return null;for(var b=this.BLOCKS.length,c=0,d=Math.floor(b/2);1<b-c;)a>=this.BLOCKS[d].block_start?c=d:b=d,d=Math.floor((b+c)/2);return this.BLOCKS[d].block},a:function(a,b){b=b||0;var c=a.charCodeAt(b),d;if(55296<=c&&56319>=c){d=a.charCodeAt(b+1);if(isNaN(d))throw"High surrogate not followed by low surrogate in fixedCharCodeAt()";
return 1024*(c-55296)+(d-56320)+65536}return 56320<=c&&57343>=c?!1:c},f:function(a){if(1>=a.length)return!0;for(var b=0;b<u.BLOCKS_WITH_UNSUPPORTED_COMBINATIONS.length;b+=1)if(-1!==a.indexOf(u.BLOCKS_WITH_UNSUPPORTED_COMBINATIONS[b]))return!1;return!0}};"use strict";
var v={EMPTY_TAGS:"area br col embed hr img input link meta param".split(" "),h:function(a,b){var c=a.head;if(null==c||void 0==c)c=a.createElement("head"),a.documentElement.appendChild(c);this.i(a);for(var d=0;d<c.childNodes.length;d++){var e=c.childNodes[d];if("meta"==e.nodeName.toLowerCase()&&"string"===typeof e.httpEquiv&&"content-type"==e.httpEquiv.toLowerCase()){d=e.getAttribute("content");if(-1!==this.EMPTY_TAGS.indexOf(d)){e.content="type=text/html;charset="+b;return}for(var c=e.content.split(";"),
f="",d=0;d<c.length;d++){var h=c[d],h=h.trim();0==h.indexOf("charset")&&(c[d]="charset = "+b);f=f+";"+c[d]}e.content=f;return}}e=a.createElement("meta");e.httpEquiv="content-type";e.content="text/html; charset="+b;c.appendChild(e)},i:function(a){var b=a.head.parentNode;a=a.head;null==b||void 0==a||null!=b.getAttribute("xmlns")&&""!=b.getAttribute("xmlns").trim()||b.setAttribute("xmlns","http://www.w3.org/1999/xhtml")},g:function(a,b){for(var c=a.head,d=0;d<c.childNodes.length;d++){var e=c.childNodes[d];
if("meta"==e.nodeName.toLowerCase()&&""==e.charset){e.charset=b;return}}d=a.createElement("meta");e=a.createAttribute("charset");e.nodeValue=b;d.attributes.setNamedItem(e);c.appendChild(d)}};"use strict";window.convertSVGInline=w;
function w(a,b){var c={},d=b.getAttribute("src"),e=x(d);if(e){e.setAttribute("amzn-src-id",b.getAttribute("amzn-src-id"));var f=document.defaultView.getComputedStyle(b).cssText+" ",f=f+e.style.cssText;e.style.cssText=f;b.parentNode.replaceChild(e,b);a.body.relayout();if(d){f=document.querySelector("head");f||(f=document.createElement("head"),document.documentElement.appendChild(f));var h=document.createElement("base");h.setAttribute("href",d);f.appendChild(h)}c.svgNode=e}else c.error="Invalid SVG link "+
d,c.errorCode=12001;return c}function x(a){if(!a)return null;var b=new XMLHttpRequest;try{b.open("GET",a,!1);b.setRequestHeader("Content-Type","image/svg+xml");b.send(null);if(200===b.status||0===b.status){var c=b.responseText;return(new DOMParser).parseFromString(c,"image/svg+xml").querySelector("svg")}return null}catch(d){return null}}"use strict";window.processNodeForEmptyXmlns=y;
function y(a,b,c){if("xhtml"===g.getExtension(c)){a=a.body.childNodes;for(c=0;c<a.length;c++)z(a[c]);for(;null!==b&&void 0!==b;)z(b),b=b.parentNode}}function z(a){null!==a&&void 0!==a&&a.nodeType===Node.ELEMENT_NODE&&null!==a.getAttribute("xmlns")&&""===a.getAttribute("xmlns").trim()&&a.attributes.removeNamedItem("xmlns")}"use strict";window.resolveFontsForGivenNode=A;
function A(a,b,c){for(var d={isFontStamped:!1},e=a.createNodeIterator(b,NodeFilter.SHOW_ALL),f=null;null!==(f=e.nextNode());)if(f.nodeType===Node.TEXT_NODE&&""!==f.nodeValue.trim()&&!f.hasValidGlyphs){for(var h=f.nodeValue.trim(),m=0,r=0,l={},n=[],p=[];m<h.length;){var k=u.a(h,m);if(!1!==k&&(k=u.c(k),-1===p.indexOf(k))){p.push(k);u.f(p)||(l=a.createElement("svg"===b.tagName?"tspan":"span"),l.textContent=h.substring(r,m),l.style.fontFamily=n.join(","),f.parentNode.insertBefore(l,f),l={},n=[],p=[k],
r=m);for(var k=u.b(k),q=0;q<k.length;q+=1){var t=k[q];!0!==l[t]&&(l[t]=!0,n.push(t))}}m+=1}f.textContent=h.substring(r);d.isFontStamped=!0;f.parentNode.style.fontFamily=n.join(",")}"svg"!==c&&(v.h(a,"utf-8"),v.g(a,"utf-8"));d.success=!0;return d};
