/*
* Copyright (c) 2015 Amazon.com. All rights reserved. 
*/
var u={error:function(f){console.error("[ERROR] : "+f)},warn:function(f){console.warn("[WARNING] : "+f)},info:function(f){console.log("[INFO]  : "+f)}},w={v:function(f){var b=require("fs");if(!b.isFile(f))return null;f=b.open(f,"r");b=f.read();f.close();return b},m:function(f,b,c){null==c&&(c="UTF-8");f=require("fs").open(f,{charset:c,mode:"w"});f.writeLine(b);f.close()},o:function(f){return require("fs").absolute(f)},s:function(f){var b=require("fs"),c=document.location.pathname,c=c.substring(0,
c.lastIndexOf(b.separator)+1);return b.isFile(c+f)?!0:!1},getExtension:function(f){if(null===f||void 0===f)return null;f=f.trim();var b=f.lastIndexOf(".");return-1===b?null:f.substring(b+1,f.length)}};"use strict";function x(f){null==f&&(f=require("system").args);if(2>f.length||3<f.length)console.log("Invalid number of arguments: Usage - scripts/rasterize.js workListFile outputFile"),phantom.exit(4);this.args=f}x.prototype.g=function(f){return f.args[1]};
function y(f){this.fs=require("fs");this.j=new x(f);this.c=[];this.b=[];this.fatal=!1}y.prototype.g=function(f){var b=f.j,c=w.o(b.g(b)),b=void 0;try{b=f.fs.read(c)}catch(a){console.log(a)}if(b){c=void 0;try{c=JSON.parse(b)}catch(e){console.log(e)}if(c)return c.workList;f.fatal=!0;f.c.push("Unable JSON parse worklist file");console.log("Unable JSON parse worklist file")}else f.fatal=!0,f.c.push("Unable read worklist"),console.log("Unable read worklist from "+c)};
function z(f){var b=f.j.args[2],c={};c.fatal=f.fatal;c.statusList=f.c;f=JSON.stringify(c);b?w.m(b,f):console.log(f)}y.prototype.exit=function(f){phantom.exit(f)};"use strict";function A(){this.i={cm:37.8,mm:3.78,q:.94,"in":96,pc:16,pt:1.33,px:1}}
A.prototype.h=function(f,b,c){b=b.clipRect;void 0!==b&&(0==b.hasPercentUnits?1==c.scaleToCanvas?(c=f.viewportSize.width/b.width,f.viewportSize={width:f.viewportSize.width,height:f.viewportSize.width/(b.width/b.height)},f.zoomFactor=c):f.clipRect={top:0,left:0,width:b.width,height:b.height}:f.clipRect={top:0,left:0,width:b.width*f.viewportSize.width/100,height:b.height*f.viewportSize.height/100})};
A.prototype.f=function(f,b){function c(a){return null==a?null:a.trim().toLowerCase()}var a={},e="#"+b.backgroundColor.toString(16),d=document.getElementsByTagName("svg");if(1>d.length)return a.error="No svg tags found",a.errorCode=12001,a;if(1<d.length)return a.error="Nested svg tags not supported",a.errorCode=12002,a;d=d[0];if(null===d.style){var g=document.createAttribute("style");g.value="background-color:"+e+";";d.setAttributeNode(g)}else d.style.backgroundColor=e;var e=c(d.getAttribute("width")),
h=c(d.getAttribute("height"));if(null!=e&&null!=h){var d=!1,k=function(a){var b={length:null,unit:null},c=a.search(/[a-zA-Z%]*$/),d=/^[0-9]*.?[0-9]+$/;if(d.test(a))return{length:a,unit:"px"};if(0>=c)return b;var e=a.substring(0,c);a=a.substring(c,a.length);return d.test(e)?"%"===a?{length:e,unit:"%"}:f.i.hasOwnProperty(a)?{length:f.i[a]*parseFloat(e),unit:"px"}:b:b},g=k(e),k=k(h);g.unit&&k.unit==g.unit?("%"===g.unit&&(d=!0),e={top:0,left:0},e.width=parseInt(g.length),e.height=parseInt(k.length),e.hasPercentUnits=
d,a.clipRect=e):(a.error="Invalid Units found "+e+" "+h,a.errorCode=12005)}else if(null!=e&&null==h||null==e&&null!=h)a.error="Invalid Units found "+e+" "+h,a.errorCode=12005;return a};"use strict";function B(){}
B.prototype.h=function(f,b,c){b=b.clipRect;if(1==c.scaleToCanvas){var a=c.zoomFactor;f.viewportSize={width:c.maxWidth,height:c.maxHeight};f.zoomFactor=a;void 0!==b&&null!==b&&(f.clipRect={top:b.top*a,left:b.left*a,width:b.width*a,height:b.height*a})}else void 0!==b&&null!==b&&(f.clipRect={top:b.top,left:b.left,width:b.width,height:b.height})};
B.prototype.f=function(f,b){var c={},a=document.querySelectorAll('[amzn-src-id="'+b.nodeID+'"]'),e="#"+b.backgroundColor.toString(16);if(1>a.length)return c.error="No tags found",c.errorCode=13001,c;a=a[0];if(null===a.style){var d=document.createAttribute("style");d.value="background-color:"+e+";";a.setAttributeNode(d)}else a.style.backgroundColor=e;void 0==document.body.style&&(e=document.createElement("STYLE"),document.body.style=e);document.body.style.margin="0px";document.body.style.padding="0px";
a.style.margin="0px";e=a.ownerDocument.defaultView.getComputedStyle(a)["box-shadow"];if(void 0===e||null===e||"none"===e)a.style.padding="0px";a.style["float"]="none";if(a!==document.body){document.body.insertBefore(a,document.body.firstChild);for(var d=document.body.childNodes,g=1,h=d.length;g<h;g++)void 0===d[g].style&&(e=document.createElement("STYLE"),d[g].style=e),d[g].style.display="none"}a.setAttribute("width",b.maxWidth);a.setAttribute("height",b.maxHeight);a.style.width=b.maxWidth+"px";a.style.height=
b.maxHeight+"px";document.body.style.width=b.maxWidth+"px";document.body.style.height=b.maxHeight+"px";document.body.relayout();e=b.validateForTransform;if(void 0!==e&&null!==e&&e){var k=a.getBoundingClientRect(),g=parseInt(a.contentBoxTopPosition),m=parseInt(a.contentBoxLeftPosition),h=parseInt(a.contentBoxRightPosition),e=parseInt(a.contentBoxBottomPosition),n=this.document.createNodeIterator(a,NodeFilter.SHOW_ELEMENT),l=null,d={};d.left=k.left;d.right=k.right;d.top=k.top;for(d.bottom=k.bottom;null!==
(l=n.nextNode());)k=d,l.nodeType==Node.ELEMENT_NODE&&(l=l.getBoundingClientRect(),k.left=Math.min(k.left,l.left),k.top=Math.min(k.top,l.top),k.right=Math.max(k.right,l.right),k.bottom=Math.max(k.bottom,l.bottom));l=a.ownerDocument.defaultView.getComputedStyle(a).boxShadow;n={left:0,right:0,top:0,bottom:0};if(void 0!==l&&null!==l&&"none"!==l)for(l=l.split(", rgb"),k=0;k<l.length;k++){var q=l[k],r=n;if(void 0!==q&&null!==q&&"none"!==q){for(var v=/(\d+(?=(px|\s)))/g,p=[],t=v.exec(q);null!=t;)p.push(parseInt(t[0])),
t=v.exec(q);for(q=p.length;4>q;q++)p.push(0);q=p[0];v=p[1];t=p[2];p=p[3];r.top=Math.max(r.top,p-v+.5*t);r.right=Math.max(r.right,p+q+.5*t);r.bottom=Math.max(r.bottom,p+v+.5*t);r.left=Math.max(r.left,p-q+.5*t)}}m=parseInt(Math.max(0,m-d.left))+parseInt(Math.max(0,n.left));h=parseInt(Math.max(0,d.right-h))+parseInt(Math.max(0,n.right));g=parseInt(Math.max(0,g-d.top))+parseInt(Math.max(0,n.top));e=parseInt(Math.max(0,d.bottom-e))+parseInt(Math.max(0,n.bottom));0==m&&0==h&&0==g&&0==e?e=!1:(a.style.display=
"inline-block",a.style.marginTop=g+"px",a.style.marginBottom=e+"px",a.style.marginLeft=m+"px",a.style.marginRight=h+"px",b.maxWidth=b.maxWidth+m+h,b.maxHeight=b.maxHeight+g+e,document.body.relayout(),e=!0)}else{if(-1===a.contentBoxTopPosition||-1===a.contentBoxBottomPosition||-1===a.contentBoxLeftPosition||-1===a.contentBoxRightPosition)c.error="Tag position is invalid",c.errorCode=13002;e=!1}if(void 0!==c.error)return c;d={};g=a.contentBoxTopPosition;h=a.contentBoxLeftPosition;m=a.contentBoxRightPosition-
h;n=a.contentBoxBottomPosition-g;d.top=g;d.left=Math.max(0,h);d.width=m;d.height=n;m>parseInt(b.maxWidth)&&(document.body.style.width="100%",a.style.width="100%");e||(c.clipRect=d);return c};"use strict";function C(){}
C.prototype.h=function(f,b,c){b=b.clipRect;if(void 0!==b){f.viewportSize={width:c.viewportWidth,height:c.viewportHeight};c.zoomFactor&&(f.zoomFactor=c.zoomFactor);var a=c.maxWidth,e=c.maxHeight,d=b.width,g=b.height;b.width>a?(d=a,g=Math.min(e,b.height)):g=Math.min(e,Math.min(b.height,b.width*c.truncatedTableRasterConfig.longTableCutAspectRatio));c=[];d<b.width&&c.push("right");g<b.height&&c.push("bottom");f.clipRect={top:b.top,left:b.left,width:d,height:g};f={};f.croppedDirections=c;return f}};
C.prototype.f=function(f,b){var c={},a=document.querySelectorAll('[amzn-src-id="'+b.nodeID+'"]'),e="#"+b.backgroundColor.toString(16);if(1>a.length)return c.error="No tags found",c.errorCode=13001,c;a=a[0];if(null===a.style){var d=document.createAttribute("style");d.value="background-color:"+e+";";a.setAttributeNode(d)}else a.style.backgroundColor=e;document.body.insertBefore(a,document.body.firstChild);for(var e=document.body.childNodes,d=1,g=e.length;d<g;d++)void 0===e[d].style&&(e[d].style=document.createElement("STYLE")),
e[d].style.display="none";a.removeAttribute("width");a.style.width="auto";a.style.maxWidth="none";a.style.minWidth="1px";a.style.margin="0px";d=document.createElement("style");d.type="text/css";d.innerHTML='td[rowspan]{position: relative;} td[rowspan]:before {position: absolute;content: "";top: -1px;left: -1px;background-color: transparent;border: solid #666 1px;width: 100%;height: 100%;';document.getElementsByTagName("head")[0].appendChild(d);document.body.relayout();if(-1===a.contentBoxTopPosition||
-1===a.contentBoxBottomPosition||-1===a.contentBoxLeftPosition||-1===a.contentBoxRightPosition)return c.error="Tag position is invalid",c.errorCode=13002,c;var e={},d=a.contentBoxTopPosition,g=a.contentBoxLeftPosition,h=document.defaultView.getComputedStyle(a),k=0,m=0;"separate"===h["border-collapse"]&&(m=h["border-spacing"].split(" "),k=parseInt(m[0]),m=parseInt(m[1]));e.top=d-m-parseInt(h["border-top-width"]);e.left=g-k-parseInt(h["border-left-width"]);e.width=a.contentBoxRightPosition-e.left+k+
parseInt(h["border-right-width"]);e.height=a.contentBoxBottomPosition-e.top+m+parseInt(h["border-bottom-width"]);if(a=a.querySelector("caption"))a.style.width=parseInt(Math.min(b.maxWidth,e.width)/b.zoomFactor)+"px",a.style.captionSide="top",captionLeftOffset=g-a.contentBoxLeftPosition,captionTopOffset=d-a.contentBoxTopPosition,d=document.defaultView.getComputedStyle(a),0<captionTopOffset&&a.style.setProperty("padding-top",parseInt(d["padding-top"])+captionTopOffset+"px","important"),0<captionLeftOffset&&
a.style.setProperty("padding-left",parseInt(d["padding-left"])+captionLeftOffset+"px","important"),0>parseInt(d["margin-bottom"])&&a.style.setProperty("margin-bottom","0px","important");c.clipRect=e;return c};"use strict";function D(f){this.a=f;this.l=f.g(f)}function E(f){f=f.a;z(f);f.exit(0)}D.prototype.onError=function(f,b,c){c.errors=b;c.errorCode=12008;f.a.c.push(c);E(f)};
var G=function F(b,c,a){var e={};b=c.l;if(a>=b.length)E(c);else if(c.a.b[a].errors){e.index=a;var d=b[a];e.sourceFile=d.sourceFile;e.errors=c.a.b[a].errors;e.errorCode=c.a.b[a].errorCode;c.a.c.push(e);F(c,c,a+1)}else{var d=b[a],g=require("webpage").create();g.onConsoleMessage=function(a){console.log(a)};g.onError=function(a){c.onError(c,a,e)};g.viewportSize={width:d.viewportWidth,height:d.viewportHeight};"truncated_table"===d.jsRasterizerType&&d.zoomFactor&&(g.zoomFactor=d.zoomFactor);d.isTextContent||
d.shouldUseInputFileToRaster||(d.inputFileToRasterURI=d.sourceFile);e.index=a;var h=d.inputFileToRasterURI,h=decodeURI(h),h=encodeURI(h);e.sourceFile=d.sourceFile;iterateImpl=function(b){if("success"!==b)e.errors="Unable to load address "+e.u,e.errorCode=12007;else{var h="svg"===d.jsRasterizerType?new A:"truncated_table"===d.jsRasterizerType?new C:new B;b=g.evaluate(h.f,h,d);var h=h.h(g,b,d),n=b.error;b=b.errorCode;n?(e.errors=n,e.errorCode=b):(g.render(d.outputPath,{format:d.format}),e.success=!0);
h&&(e.croppedDirections=h.croppedDirections)}c.a.c.push(e);g.close();F(c,c,a+1)};d.isReloadRequired?(g.reload(),window.setTimeout(function(){g.open(h,function(a){iterateImpl(a)})},500)):(g.onLoadFinished=function(a){iterateImpl(a)},g.open(h))}};"use strict";phantom.injectJs("rasterizerScriptInjector.js")||(console.error("[ERROR] : Initialization Error: Failed to Inject rasterizerScriptInjector.js"),phantom.exit(1));
phantom.onError=function(f,b){try{var c=[f];b&&b.length&&b.forEach(function(a){c.push((a.file||a.sourceURL)+": "+a.line)});console.log(c.join("\n"));H.c=[{index:0,errors:f,errorCode:12008}];H.fatal=!1;z(H);phantom.exit(0)}catch(a){console.log(a),phantom.exit(1)}};var H;H=new y;var I=new D(H);
(function J(b,c,a){b=c.l;if(a>=b.length)G(c,c,0);else{var e=b[a],d={},g=require("webpage").create();g.onConsoleMessage=function(a){console.log(a)};g.onError=function(a){c.onError(c,a,d)};g.viewportSize={width:e.viewportWidth,height:e.viewportHeight};"truncated_table"===e.jsRasterizerType&&e.zoomFactor&&(g.zoomFactor=e.zoomFactor);d.index=a;b=e.sourceFile;var h=w.getExtension(b);e.shouldUseInputFileToRaster="xhtml"===h||"xml"===h;e.shouldUseInputFileToRaster&&(b=e.inputFileToRasterURI);b=decodeURI(b);
b=encodeURI(b);d.sourceFile=e.sourceFile;!1===e.isTextContent?(d.success=!0,c.a.b.push(d),J(c,c,a+1)):g.open(b,function(b){"success"!==b?(d.errors="Unable to load address "+d.u,d.errorCode=12007,c.a.b.push(d),g.close(),J(c,c,a+1)):window.setTimeout(function(){g.injectJs("rasterizerProcessor.js")||(w.s("rasterizerProcessor.js")||console.log("File rasterizerProcessor.js doesnt exist"),u.error("Internal Failure : Error in injecting rasterizerProcessor.js"),phantom.exit(ErrorCode.INJECTION_FAILURE));
var b=g.evaluate(function(a){var b,c={};if("svg"===a.jsRasterizerType){if(b=document.querySelector("svg"),!b)return c.error="No svg tags found",c.errorCode=13001,c}else{b=document.querySelectorAll('[amzn-src-id="'+a.nodeID+'"]');if(1>b.length)return c.error="No tags found",c.errorCode=13001,c;b=b[0];if("img"===b.tagName.toLowerCase()){c=convertSVGInline(document,b);if(c.error)return c;b=c.svgNode}}var d=b.querySelector("caption");if(d){var e=document.defaultView.getComputedStyle(d,":before").content,
d=document.defaultView.getComputedStyle(d,":after").content;if(""!==e||""!==d)return c.error="Text found in caption :before or :after selector",c.errorCode=13006,c}processNodeForEmptyXmlns(document,b,a.sourceFile);c=resolveFontsForGivenNode(document,b,a.jsRasterizerType);c.isReloadRequired="svg"===b.tagName.toLowerCase()&&c.isFontStamped;return c},e);if(b.error)d.errors=b.error,d.errorCode=b.errorCode,c.a.b.push(d);else try{w.m(e.inputFileToRaster,g.content,"UTF-8"),e.isReloadRequired=b.isReloadRequired,
d.success=!0,c.a.b.push(d)}catch(h){d.errors="Unable to store html content to location "+e.inputFileToRaster,d.errorCode=12001,c.a.b.push(d)}g.release();J(c,c,a+1)},200)})}})(I,I,0);
